spring:
  application:
    name: wms
  profiles:
    active: dev
  config:
    import: 
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# 在 banner.txt 中显示项目版本，使用 @project.version@ 从 pom.xml 获取
project:
  version: @project.version@
